20220830-090608  NO DATA TO UPDATE
20220830-090924  NO DATA TO UPDATE
20220830-091316  NO DATA TO UPDATE
20220830-091609  NO DATA TO UPDATE
20220830-101609  NO DATA TO UPDATE
20220830-104439  SUCCESS  :  36
20220830-111605  SUCCESS  :  15
20220830-121608  SUCCESS  :  13
20220830-131613  SUCCESS  :  18
20220830-141609  SUCCESS  :  12
20220830-151610  SUCCESS  :  14
20220830-161606  SUCCESS  :  16
20220830-171611  SUCCESS  :  22
20220830-181606  SUCCESS  :  23
20220830-191605  SUCCESS  :  15
20220830-201607  SUCCESS  :  18
20220830-211610  SUCCESS  :  14
20220830-221634  SUCCESS  :  15
20220830-231610  SUCCESS  :  22
20220831-101607  SUCCESS  :  50
20220831-102404  SUCCESS  :  2
20220831-111634  SUCCESS  :  21
20220831-121640  SUCCESS  :  11
20220831-131639  SUCCESS  :  24
20220831-141644  SUCCESS  :  13
20220831-160638  SUCCESS  :  37
20220831-163614  SUCCESS  :  5
20220831-170639  SUCCESS  :  9
20220831-173643  SUCCESS  :  8
20220831-180637  SUCCESS  :  4
20220831-183633  SUCCESS  :  12
20220831-190640  SUCCESS  :  5
20220831-193638  SUCCESS  :  6
20220831-200649  SUCCESS  :  12
20220831-203635  SUCCESS  :  5
20220831-210635  SUCCESS  :  6
20220831-213637  SUCCESS  :  11
20220831-220636  SUCCESS  :  7
20220831-223638  SUCCESS  :  6
20220831-230648  SUCCESS  :  13
20220831-233631  SUCCESS  :  8
20220901-000658  SUCCESS  :  70
20220901-003642  SUCCESS  :  16
20220901-010630  SUCCESS  :  3
20220901-013633  SUCCESS  :  3
20220901-020635  SUCCESS  :  3
20220901-023637  SUCCESS  :  1
20220901-030633  NO DATA TO UPDATE
20220901-033633  NO DATA TO UPDATE
20220901-040632  SUCCESS  :  1
20220901-043632  NO DATA TO UPDATE
20220901-050629  SUCCESS  :  1
20220901-053628  SUCCESS  :  3
20220901-060606  SUCCESS  :  1
20220901-063630  SUCCESS  :  3
20220901-070604  SUCCESS  :  6
20220901-073607  SUCCESS  :  2
20220901-080602  SUCCESS  :  7
20220901-083626  SUCCESS  :  8
20220901-090632  SUCCESS  :  12
20220901-093630  SUCCESS  :  14
20220901-100628  SUCCESS  :  13
20220901-103636  SUCCESS  :  10
20220901-110626  SUCCESS  :  12
20220901-113619  SUCCESS  :  10
20220901-120634  SUCCESS  :  9
20220901-123627  SUCCESS  :  13
20220901-130630  SUCCESS  :  21
20220901-133632  SUCCESS  :  19
20220901-140626  SUCCESS  :  16
20220901-143629  SUCCESS  :  15
20220901-150701  SUCCESS  :  11
20220901-153626  SUCCESS  :  16
20220901-160626  SUCCESS  :  16
20220901-163641  SUCCESS  :  16
20220901-170640  SUCCESS  :  18
20220901-173639  SUCCESS  :  15
20220901-180643  SUCCESS  :  11
20220901-183642  SUCCESS  :  16
20220901-190642  SUCCESS  :  13
20220901-193620  SUCCESS  :  8
20220906-160647  SUCCESS  :  70
20220906-163642  SUCCESS  :  9
20220906-170639  SUCCESS  :  14
20220906-173643  SUCCESS  :  13
20220906-180642  SUCCESS  :  9
20220906-183640  SUCCESS  :  13
20220906-190637  SUCCESS  :  10
20220906-193641  SUCCESS  :  6
20220906-200639  SUCCESS  :  12
20220906-203646  SUCCESS  :  8
20220906-210617  SUCCESS  :  8
20220906-213643  SUCCESS  :  5
20220906-220647  SUCCESS  :  8
20220906-223647  SUCCESS  :  14
20220906-230641  SUCCESS  :  19
20220906-233637  SUCCESS  :  32
20220907-000638  SUCCESS  :  70
20220907-003638  SUCCESS  :  4
20220907-010635  SUCCESS  :  10
20220907-013639  SUCCESS  :  6
20220907-020635  NO DATA TO UPDATE
20220907-023638  SUCCESS  :  4
20220907-030640  SUCCESS  :  4
20220907-033638  SUCCESS  :  1
20220907-040636  NO DATA TO UPDATE
20220907-043638  NO DATA TO UPDATE
20220907-050637  SUCCESS  :  2
20220907-053643  SUCCESS  :  1
20220907-060637  SUCCESS  :  1
20220907-063635  SUCCESS  :  2
20220907-070642  SUCCESS  :  3
20220907-073612  SUCCESS  :  4
20220907-080636  SUCCESS  :  3
20220907-083640  SUCCESS  :  4
20220907-090642  SUCCESS  :  8
20220907-093644  SUCCESS  :  24
20220907-100640  SUCCESS  :  35
20220907-103618  SUCCESS  :  27
20220907-110640  SUCCESS  :  24
20220907-113643  SUCCESS  :  15
20220907-120618  SUCCESS  :  27
20220907-123639  SUCCESS  :  18
20220907-130617  SUCCESS  :  12
20220907-133647  SUCCESS  :  19
20220907-140645  SUCCESS  :  8
20220907-143645  SUCCESS  :  10
20220907-150642  SUCCESS  :  12
20220907-153632  SUCCESS  :  12
20220907-160612  SUCCESS  :  14
20220907-163641  SUCCESS  :  14
20220907-170640  SUCCESS  :  14
20220907-173642  SUCCESS  :  10
20220907-180637  SUCCESS  :  6
20220907-183637  SUCCESS  :  16
20220907-190637  SUCCESS  :  5
20220907-193635  SUCCESS  :  6
20220907-200648  SUCCESS  :  7
20220913-090635  SUCCESS  :  69
20220913-093633  SUCCESS  :  14
20220913-100637  SUCCESS  :  16
20220913-103643  SUCCESS  :  11
20220913-110608  SUCCESS  :  6
20220913-113633  SUCCESS  :  10
20220913-120634  SUCCESS  :  10
20220913-123630  SUCCESS  :  18
20220913-130630  SUCCESS  :  10
20220913-133637  SUCCESS  :  9
20220913-140630  SUCCESS  :  8
20220913-143633  SUCCESS  :  10
20220913-150634  SUCCESS  :  8
20220913-153630  SUCCESS  :  8
20220913-160639  SUCCESS  :  5
20220913-163634  SUCCESS  :  14
20220913-170614  SUCCESS  :  5
20220913-173610  SUCCESS  :  10
20220913-180626  SUCCESS  :  15
20220913-183628  SUCCESS  :  11
20220913-190630  SUCCESS  :  6
20220913-193629  SUCCESS  :  9
20220913-200632  SUCCESS  :  15
20220913-203628  SUCCESS  :  11
20220913-210635  SUCCESS  :  11
20220913-213628  SUCCESS  :  28
20220913-220609  SUCCESS  :  50
SPECIAL CHARACTER IN TITLE
SPECIAL CHARACTER IN TITLE
20220913-223635  SUCCESS  :  68
20220913-230627  SUCCESS  :  65
20220913-233630  SUCCESS  :  49
20220914-000622  SUCCESS  :  70
20220914-003624  SUCCESS  :  40
20220914-010629  SUCCESS  :  20
20220914-013623  SUCCESS  :  16
20220914-020621  SUCCESS  :  6
20220914-023625  SUCCESS  :  9
20220914-030620  SUCCESS  :  7
20220914-033610  SUCCESS  :  3
20220914-040612  SUCCESS  :  4
20220914-043640  SUCCESS  :  5
20220914-050624  SUCCESS  :  12
20220914-053626  SUCCESS  :  7
20220914-060603  SUCCESS  :  10
20220914-063626  SUCCESS  :  13
20220914-070623  SUCCESS  :  21
20220914-073632  SUCCESS  :  29
20220914-080632  SUCCESS  :  29
20220914-083603  SUCCESS  :  33
20220914-090624  SUCCESS  :  35
20220914-093608  SUCCESS  :  48
20220914-150630  SUCCESS  :  70
20220914-153624  SUCCESS  :  10
20220914-160629  SUCCESS  :  7
20220914-163628  SUCCESS  :  10
20220914-170627  SUCCESS  :  10
20220914-173625  SUCCESS  :  15
20220914-180625  SUCCESS  :  11
20220914-183628  SUCCESS  :  8
20220914-190631  SUCCESS  :  16
20220914-193742  SUCCESS  :  9

20220922-085435  SUCCESS  :  69
20220922-090626  SUCCESS  :  11
20220922-093629  SUCCESS  :  48
20220922-100628  SUCCESS  :  37
20220922-103629  SUCCESS  :  36
20220922-110625  SUCCESS  :  41
20220922-113631  SUCCESS  :  22
20220922-120626  SUCCESS  :  13
20220922-123624  SUCCESS  :  22
20220922-130630  SUCCESS  :  16
20220922-133626  SUCCESS  :  18
20220922-140626  SUCCESS  :  14
20220922-143626  SUCCESS  :  12
20220922-150629  SUCCESS  :  18
20220922-153626  SUCCESS  :  21
20220922-160626  SUCCESS  :  21
20220922-163628  SUCCESS  :  17
20220922-170626  SUCCESS  :  19
20220922-173627  SUCCESS  :  9
20220922-180625  SUCCESS  :  20
20220922-183624  SUCCESS  :  18
20220922-190622  SUCCESS  :  11
20220922-193633  SUCCESS  :  5
20220922-200625  SUCCESS  :  16
20220922-203601  SUCCESS  :  14
20220922-210626  SUCCESS  :  6
20220922-213631  SUCCESS  :  13
20220922-220623  SUCCESS  :  6
20220922-223627  SUCCESS  :  17
20220922-230621  SUCCESS  :  23
20220922-233625  SUCCESS  :  20
20220923-000624  SUCCESS  :  70
SPECIAL CHARACTER IN TITLE
20220923-003621  SUCCESS  :  22
20220923-010619  SUCCESS  :  7
20220923-013621  SUCCESS  :  4
20220923-020621  SUCCESS  :  8
20220923-023622  SUCCESS  :  2
20220923-030623  SUCCESS  :  3
20220923-033630  SUCCESS  :  3
20220923-040622  SUCCESS  :  3
20220923-043606  SUCCESS  :  3
20220923-050626  SUCCESS  :  1
20220923-053624  NO DATA TO UPDATE
20220923-060623  NO DATA TO UPDATE
20220923-063624  SUCCESS  :  2
20220923-070631  NO DATA TO UPDATE
SPECIAL CHARACTER IN TITLE
20220923-073628  SUCCESS  :  11
20220923-080628  SUCCESS  :  7
20220923-083629  SUCCESS  :  7
20220923-090632  SUCCESS  :  12
20220923-093613  SUCCESS  :  30
20220923-100612  SUCCESS  :  18
20220923-103636  SUCCESS  :  17
20220923-110649  SUCCESS  :  20
Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.719
  (Session info: headless chrome=105.0.5195.52)

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 276.938
  (Session info: headless chrome=105.0.5195.52)

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 256.055
  (Session info: headless chrome=105.0.5195.52)

20220926-093639  SUCCESS  :  69
20220926-100636  SUCCESS  :  52
SPECIAL CHARACTER IN TITLE
20220926-103635  SUCCESS  :  65
20220926-110628  SUCCESS  :  47
20220926-113629  SUCCESS  :  38
20220926-120633  SUCCESS  :  26
20220926-123632  SUCCESS  :  31
20220926-130634  SUCCESS  :  45
20220926-133635  SUCCESS  :  59
20220926-140632  SUCCESS  :  57
20220926-143636  SUCCESS  :  63
20220926-150636  SUCCESS  :  51
20220926-153608  SUCCESS  :  40
20220926-160628  SUCCESS  :  37
20220926-163616  SUCCESS  :  26
20220926-170637  SUCCESS  :  23
20220926-173610  SUCCESS  :  19
20220926-180633  SUCCESS  :  32
20220926-183609  SUCCESS  :  23
20220926-190638  SUCCESS  :  22
20220926-193614  SUCCESS  :  14
20220926-200633  SUCCESS  :  2
20220926-203635  SUCCESS  :  19
20220926-210633  SUCCESS  :  12
20220926-213633  SUCCESS  :  22
20220926-220630  SUCCESS  :  17
20220926-223606  SUCCESS  :  21
20220926-230632  SUCCESS  :  22
20220926-233630  SUCCESS  :  20
20220927-000631  SUCCESS  :  69
SPECIAL CHARACTER IN TITLE
20220927-003635  SUCCESS  :  16
20220927-010633  SUCCESS  :  8
20220927-013632  SUCCESS  :  10
20220927-020628  SUCCESS  :  5
20220927-023631  SUCCESS  :  4
20220927-030633  SUCCESS  :  1
20220927-033635  SUCCESS  :  1
20220927-040631  SUCCESS  :  2
20220927-043628  NO DATA TO UPDATE
20220927-050630  NO DATA TO UPDATE
20220927-053631  NO DATA TO UPDATE
20220927-060631  SUCCESS  :  3
20220927-063632  SUCCESS  :  1
20220927-070629  SUCCESS  :  3
20220927-073627  SUCCESS  :  3
20220927-080638  SUCCESS  :  10
20220927-083637  SUCCESS  :  23
20220927-090642  SUCCESS  :  23
Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.495
  (Session info: headless chrome=105.0.5195.52)

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 69, in <module>
    driver = webdriver.Chrome('/home/lsi8505/chromedriver',options=options)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 274.560
  (Session info: headless chrome=105.0.5195.52)

20220927-133613  SUCCESS  :  50
20220927-140634  SUCCESS  :  14
20220927-143635  SUCCESS  :  20
20220927-150640  SUCCESS  :  31
20220927-153611  SUCCESS  :  11
20220927-160632  SUCCESS  :  10
20220927-163605  SUCCESS  :  13
20220927-170636  SUCCESS  :  20
20220927-173606  SUCCESS  :  15
20220927-180632  SUCCESS  :  9
20220927-183632  SUCCESS  :  14
20220927-190634  SUCCESS  :  13
20220927-193640  SUCCESS  :  15
20220927-200637  SUCCESS  :  8
20220927-203641  SUCCESS  :  8
20220927-210608  SUCCESS  :  17
20220927-213632  SUCCESS  :  17
20220927-220627  SUCCESS  :  20
SPECIAL CHARACTER IN TITLE
20220927-223634  SUCCESS  :  9
20220927-230632  SUCCESS  :  13
20220927-233636  SUCCESS  :  23
20220928-000629  SUCCESS  :  70
20220928-003634  SUCCESS  :  8
20220928-010638  SUCCESS  :  11
20220928-013629  SUCCESS  :  15
20220928-020624  SUCCESS  :  2
20220928-023630  SUCCESS  :  2
20220928-030631  SUCCESS  :  2
20220928-033634  SUCCESS  :  2
20220928-040626  SUCCESS  :  1
20220928-043624  SUCCESS  :  1
20220928-050628  SUCCESS  :  1
20220928-053625  NO DATA TO UPDATE
20220928-060630  SUCCESS  :  1
20220928-063634  NO DATA TO UPDATE
20220928-070605  SUCCESS  :  4
20220928-073635  SUCCESS  :  4
20220928-080630  SUCCESS  :  9
20220928-083626  SUCCESS  :  12
20220928-090635  SUCCESS  :  17
20220928-093636  SUCCESS  :  24
20220928-100635  SUCCESS  :  14
20220928-103606  SUCCESS  :  22
20220928-110623  SUCCESS  :  50
20220928-113632  SUCCESS  :  70
20220928-120628  SUCCESS  :  70
20220928-123631  SUCCESS  :  70
20220928-130635  SUCCESS  :  31
20220928-133614  SUCCESS  :  46
20220928-140606  SUCCESS  :  5
20220928-143632  SUCCESS  :  52
20220928-150630  SUCCESS  :  46
20220928-153638  SUCCESS  :  31
20220928-160656  SUCCESS  :  31
Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 276.275
  (Session info: headless chrome=105.0.5195.52)

SPECIAL CHARACTER IN TITLE
SPECIAL CHARACTER IN TITLE
20220928-175131  SUCCESS  :  68
Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=105.0.5195.52)

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 69, in <module>
    driver = webdriver.Chrome('/home/lsi8505/chromedriver',options=options)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 69, in <module>
    driver = webdriver.Chrome('/home/lsi8505/chromedriver',options=options)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 69, in <module>
    driver = webdriver.Chrome('/home/lsi8505/chromedriver',options=options)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 69, in <module>
    driver = webdriver.Chrome('/home/lsi8505/chromedriver',options=options)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 69, in <module>
    driver = webdriver.Chrome('/home/lsi8505/chromedriver',options=options)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: headless chrome=105.0.5195.52)

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=105.0.5195.52)

Traceback (most recent call last):
  File "/home/lsi8505/miraeasset/crawling/src/BLIND_STOCK.py", line 70, in <module>
    driver.get(url)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lsi8505/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -18.068
  (Session info: headless chrome=105.0.5195.52)

SPECIAL CHARACTER IN TITLE
20220929-110628  SUCCESS  :  68
SPECIAL CHARACTER IN TITLE
20220929-113626  SUCCESS  :  9
SPECIAL CHARACTER IN TITLE
20220929-120634  SUCCESS  :  16
SPECIAL CHARACTER IN TITLE
20220929-123630  SUCCESS  :  12
20220929-130606  SUCCESS  :  9
20220929-133608  SUCCESS  :  12
20220929-140630  SUCCESS  :  8
20220929-143631  SUCCESS  :  9
20220929-150612  SUCCESS  :  19
20220929-153634  SUCCESS  :  39
20220929-160611  SUCCESS  :  24
